Rna fixup
automl/CARL pull request #46
Opened 2022-04-29 09:09 UTC by TheEimer

RNA is now better documented and more easily runnable. There's also an option to subsample the datasets instead of always using all instances per context.

The thing that's missing right now are more context options like filtering by solvers or GC-content, but those aren't easily extractable from our data right now, so that's a separate work package all together.

2022-04-29 09:14 UTC, TheEimer commented
Wow, we should resolve the flake8 issues at some point... but I'd like to fix the dist check, I just don't 100% understand what's failing there, any hints?

2022-04-29 13:23 UTC, benjamc requested changes
Looks fine! Cleaner than before.

I think we need to write some tests for this. A test for instantiating the env would be good. Of course we could use mock ups so we don't need to install the library everytime :)

2022-04-29 13:23 UTC, benjamc commented on carl/envs/rna/carl_rna.py
> +        #self.data_location = "/home/eimer/Dokumente/git/CARL/carl/envs/rna/learna/data"
- [ ] Remove your dir

2022-04-29 13:24 UTC, TheEimer commented on carl/envs/rna/carl_rna_definitions.py
> +#FIXME: how much sense do these make? Eterna solvers are unique and I'm not sure how to get the solvers for taneda
Nope, this is something we should clarify with Frederik, though

2022-04-29 13:25 UTC, TheEimer commented on carl/context/sampling.py
> +                elif context_feature_type == "conditional":
No, I'll extend the test before merging this

2022-04-29 13:26 UTC, TheEimer commented
> Looks fine! Cleaner than before.
> 
> I think we need to write some tests for this. A test for instantiating the env would be good. Of course we could use mock ups so we don't need to install the library everytime :)

Instantiating will be fine, all the data and stuff is only needed at reset afaik, so we can test that part :D

2022-05-04 09:48 UTC, TheEimer commented
I removed the code leftovers and added a test for instantiating the RNA env and changing the context.
I didn't test the conditional sampling yet because there is no sampling test at all right now - we should add that when we fix the dist as well.

2022-05-25 10:23 UTC, benjamc approved these changes

2022-05-25 11:44 UTC, merged