enhancement: Environment Reconciliation
automl/CARL pull request #95
Opened 2023-06-21 08:13 UTC by amsks

Changes: 
- DMC 
- Brax

Environments checked and reconciled for newer changes from the train.

2023-06-28 08:50 UTC, TheEimer commented on .gitmodules
That is definitely a wrong change, no? Why include the workshop paper but remove mario? Can we still install it without the submodules?

2023-06-28 08:51 UTC, TheEimer commented on CITATION.bib
Deleting this is also bad :D

2023-06-28 08:51 UTC, TheEimer commented on README.md
The spaces are okay, but cite us should not be gone!

2023-06-28 08:53 UTC, TheEimer commented on carl/envs/___carl_brax_env.py
I'm fairly sure this can be deleted

2023-06-28 08:54 UTC, TheEimer commented on carl/envs/__init__.py
We should aim to rename the brax dir to brax again

2023-06-28 08:56 UTC, TheEimer commented on carl/envs/carl_env.py
Did we change the hide context default on purpose @benjamc ?

2023-06-28 09:03 UTC, TheEimer commented on carl/envs/mario/pcg_smb_env/toadgan/generate_sample.py
None of these should be in here, please re-add the submodule instead. Why are they commited to main?

2023-06-28 09:04 UTC, TheEimer commented on docs/source/api/index.rst
Why are the docs deleted? Re-add please!

2023-06-28 09:05 UTC, TheEimer commented on experiments/Readme.md
The experiments were explicitly NOT supposed to be on this branch, please remove

2023-06-28 09:06 UTC, TheEimer commented on notes/run_context_efficiency.sh
These notes should also be removed

2023-06-28 09:06 UTC, TheEimer commented on requirements_clone.txt
delete

2023-06-28 09:07 UTC, TheEimer requested changes
Please see my comments and fix

2023-07-13 16:05 UTC, amsks commented on CITATION.bib
Readded the old citation. However, which citation do we want to retain? CARL or Contextualize me?

2023-07-13 16:06 UTC, amsks commented on .gitmodules
Readded

2023-07-13 16:06 UTC, amsks commented on README.md
Readded

2023-07-13 16:09 UTC, amsks commented on carl/envs/__init__.py
Changed

2023-07-13 16:12 UTC, amsks commented on carl/envs/___carl_brax_env.py
Done

2023-07-13 16:22 UTC, amsks commented on requirements_clone.txt
Done

2023-07-13 16:23 UTC, amsks commented on notes/run_context_efficiency.sh
Removed

2023-07-13 16:33 UTC, amsks commented on docs/source/api/index.rst
readded

2023-07-13 16:34 UTC, amsks commented on carl/envs/carl_env.py
Not sure about thi, @benjaminc?

2023-07-13 16:35 UTC, amsks commented on carl/envs/mario/pcg_smb_env/toadgan/generate_sample.py
readded submodules

2023-07-14 08:08 UTC, TheEimer commented on CITATION.bib
Contextualize Me

2023-07-14 10:33 UTC, TheEimer commented
I'll merge this with failing tests since we're overhauling everything in #89 anyway

2023-07-14 10:34 UTC, merged

2023-07-14 10:37 UTC, TheEimer commented
Aditya, that's the wrong branch! Please open a PR on development!